### ISSUE TITLE
Not enough issues 

### ISSUE THREAD

**Issue by ControlCplusControlV** [yacineMTB/talk#1]
Would be easier to help if there are more issues, otherwise the best I can really do is nits or orthogonal feature prs as is OSS tradition :)

Maybe track the fixMe's somewhere, would make a PR but don't want to repeat work if you are already on it

**Comment by yacineMTB** [comment]
Ah, of course!

Creating some, like
https://github.com/yacineMTB/talk/issues/3

**Comment by yacineMTB** [comment]
Another one, more research but quite fun!
https://github.com/yacineMTB/talk/issues/4

**Comment by jmanhype** [comment]
HELP I HAVE MAJOR ISSUES

**Comment by jmanhype** [comment]
segmentation fault when trying to use the record.sh 

Im on windows 

can you explain how to install piper and SOX on windows?

**Comment by ControlCplusControlV** [comment]
Fixed in #4 #3
