### ISSUE TITLE
Runpod / Docker support

### ISSUE THREAD

**Issue by Glavin001** [yacineMTB/talk#13]
## Use Case

For those, such as myself (MacBook Pro, Intel + AMD GPU), without powerful GPUs, it would be great to self host on a serverless GPU service (e.g. Runpod).

Also having Docker build would make setup much easier. We could distribute pre-build Docker images for quick installation.

### Runpod

Here are some related examples I found:
- Whisper
  - https://github.com/runpod-workers/worker-whisper
  - https://github.com/runpod-workers/worker-faster_whisper
- GGML language models: https://github.com/OpenAccess-AI-Collective/servereless-runpod-ggml

**Comment by jmanhype** [comment]
I have a windows system 
Running super 2080
32gb ram

its not linux so whenever i try to run the record it breaks segmentation

**Comment by yacineMTB** [comment]
I'll make sure that each individual component is compilable, and I'll make it such that the folks who run it are responsible for compiling the components themselves, maybe with some helper scripts

Any issue is resolvable with enough elbow grease :) 
I find that the difficulty to run things ends up being a positive filter, especially early on
Also I kinda don't like docker

**Comment by jmanhype** [comment]
Canceerrr lol
