### ISSUE TITLE
Allowing interruptions

### ISSUE THREAD

**Issue by choombaa** [yacineMTB/talk#30]
The user may want to interrupt the LLM while it's speaking, so that it doesn't ramble.

I think that a simple "detect user talking" solution might be good enough, since in normal human conversation, a person could interrupt with any sentence. If the user speaks above a certain word threshold while the LLM is speaking, the LLM should stop and yield.

I am working on this right now, leaving this issue as a placeholder.

**Comment by choombaa** [comment]
The crux of this work seems to be interrupting the llamaInvoke() data stream. Is anyone familiar with how to stop streams with axios? I gave it a shot, but got stuck after neither AbortController or CancelToken worked. Will open a WIP PR for this.

**Comment by choombaa** [comment]
PR open: https://github.com/yacineMTB/talk/pull/36

This depends on a patch to llama.cpp

**Comment by choombaa** [comment]
https://github.com/yacineMTB/llama.cpp/pull/5

**Comment by yacineMTB** [comment]
merged your diff big guy, good shit
