### ISSUE TITLE
Audio process stops after a few minutes

### ISSUE THREAD

**Issue by choombaa** [yacineMTB/talk#38]
After ~4 minutes, the audio process (record_audio.sh) stops sending chunks.

For some reason, adding a listener on stderr fixes the issue:

```
audioProcess.stderr.on('data', (data) => {
  console.log(data);
});
```

Not sure why this works, but the application works fine for 45+ minutes with this snippet.

**Comment by jmanhype** [comment]
what file??

**Comment by yacineMTB** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm wtf?

**Comment by jmanhype** [comment]
I can concur

**Comment by yacineMTB** [comment]
Oh of course
the stream gets filled up
because we're not consuming the events, it basically just like fills up
otherwise, rec would basically leak (keep on taking more RAM over time)
so it blocks to stop this from happening
i will patch
cheers lads

**Comment by yacineMTB** [comment]
https://github.com/yacineMTB/talk/commit/e81b8a6c02e67b4cad4c8a5326296cb713025d07

**Comment by choombaa** [comment]
Omg this was actually the fix
